version: "3.9"

services:
  # -------------------------------------------------------
  # The scm-manager is used to handle all source code and
  # revision management
  scm:
    extends:
      file: scm/docker-compose.yml
      service: scm

  # -------------------------------------------------------
  # Redmine is a flexible project management web application.
  # Written using the Ruby on Rails framework, it is
  # cross-platform and cross-database.
  redmine:
    extends:
      file: redmine/docker-compose.yml
      service: redmine

    depends_on:
      - mysql

  # -------------------------------------------------------
  # MySQL is an open-source relational database management
  # system (RDBMS)
  mysql:
    extends:
      file: mysql/docker-compose.yml
      service: mysql

volumes:
    scm: {}
    mysql: {}