version: '3.7'

services:

    scm:
        image: scmmanager/scm-manager:latest
        restart: always
        
        container_name: catweazle-scm
        hostname: catweazle-scm

        ports:
            - "8080:8080"
            # if the ssh plugin is used
            # - "2222:2222"

        volumes:
            - scm:/var/lib/scm

    redmine:
        image: redmine
        restart: always
        
        container_name: catweazle-rm
        hostname: catweazle-rm
        
        ports:
            - "3000:3000"
        
        environment:
            REDMINE_DB_MYSQL: catweazle-db
            REDMINE_DB_PASSWORD: example
            REDMINE_SECRET_KEY_BASE: supersecretkey

    db:
        image: mysql:5.7
        restart: always
        
        container_name: catweazle-db
        hostname: catweazle-db
        
        volumes:
            - db:/var/lib/mysql
        
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: redmine
    
volumes:
  scm: {}
  db: {}
