version: "3.9"

services:

    redmine:
        image: redmine
        restart: always

        container_name: catweazle-rm
        hostname: catweazle-rm

        ports:
            - "3000:3000"

        environment:
            REDMINE_DB_MYSQL: catweazle-db
            REDMINE_DB_PASSWORD: example
            REDMINE_SECRET_KEY_BASE: supersecretkey
