version: "3.9"

services:

    mysql:
        image: mysql:5.7
        restart: always

        container_name: catweazle-db
        hostname: catweazle-db

        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: redmine

        volumes:
          - mysql:/var/lib/mysql

volumes:
    mysql: {}
