FROM perl:5.36
MAINTAINER Alexander Thiel (alex@alx-development.de)

# Installing the dependencies
RUN cpan Log::Log4perl
RUN cpan Imager::QRCode Data::Uniqid
RUN cpan Net::Stomp JSON
RUN cpan Config::IniFiles
